# based on https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake
  - standard

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  NewCops: disable
